DG Setup - Manual
=================
Clone the machines, 2nd machine with new mac addresses 

Change host names and ip address 

nmcli general hostname
nmcli general hostname primary.localdomain
nmcli general hostname

nmcli general hostname
nmcli general hostname standby.localdomain
nmcli general hostname

change ip addresses of 2 machines, disable ip6

edit and update /etc/hosts
vi /etc/hosts 

192.168.1.21 primary.localdomain primary 
192.168.1.22 standby.localdomain standby


service systemd-hostnamed restart
hostname
hostname -i
 
ifconfig -a

service network restart 


Drop database on standby:

sqlplus / as sysdba
shutdown immediate;
STARTUP MOUNT EXCLUSIVE RESTRICT;
DROP DATABASE;



Primary Side 
============
su - oracle 
env | grep ORA

sqlplus / as sysdba

set linesize 300
COL FORCE_LOGGING FOR A10 
COL DB_UNIQUE_NAME FOR A15
SELECT name, DB_UNIQUE_NAME, open_mode, log_mode, database_role, FORCE_LOGGING, FLASHBACK_ON FROM v$database;

ALTER SYSTEM SET LOG_ARCHIVE_DEST_1 = 'LOCATION=USE_DB_RECOVERY_FILE_DEST' SCOPE=BOTH;
(if FRA is enabled we dont need to set DEST_1)
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ALTER SYSTEM SWITCH LOGFILE;
SELECT NAME FROM V$ARCHIVED_LOG;


ALTER SYSTEM SET DB_UNIQUE_NAME='HYD' SCOPE=SPFILE;

ALTER DATABASE FORCE LOGGING;

ALTER SYSTEM SET DB_FLASHBACK_RETENTION_TARGET = 2880 SCOPE=BOTH;

ALTER DATABASE FLASHBACK ON;


--Standby Redo Log files
SET LINESIZE 200;
SET PAGESIZE 50;
SELECT GROUP#,BYTES/1024/1024 MB FROM V$LOG;
SELECT THREAD#,INSTANCE FROM V$THREAD;

COL MEMBER FOR A60
SELECT GROUP#,STATUS,TYPE,MEMBER FROM V$LOGFILE ORDER BY GROUP#;

alter database add standby logfile group 11 '/u01/app/oracle/oradata/ORADB/redo11.log' size 200m;
alter database add standby logfile group 12 '/u01/app/oracle/oradata/ORADB/redo12.log' size 200m;
alter database add standby logfile group 13 '/u01/app/oracle/oradata/ORADB/redo13.log' size 200m;
alter database add standby logfile group 14 '/u01/app/oracle/oradata/ORADB/redo14.log' size 200m;
SELECT GROUP#,THREAD#,SEQUENCE#,ARCHIVED,STATUS FROM V$STANDBY_LOG ORDER BY GROUP#;

ALTER SYSTEM SET STANDBY_FILE_MANAGEMENT = 'AUTO' SCOPE = BOTH;

ALTER SYSTEM SET LOG_ARCHIVE_CONFIG='DG_CONFIG=(HYD,PUNE)' SCOPE=BOTH;

ALTER SYSTEM SET LOG_ARCHIVE_DEST_2='SERVICE=ORADB_S2 ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=PUNE' SCOPE=BOTH;

ALTER SYSTEM SET ARCHIVE_LAG_TARGET=1800 SCOPE=BOTH;

--should be EXCLUSIVE
SHOW PARAMETER REMOTE_LOGIN_PASSWORDFILE;

# FAL = Fetch Archive Log 
ALTER SYSTEM SET FAL_SERVER = 'ORADB_S2' SCOPE = BOTH;
ALTER SYSTEM SET FAL_CLIENT = 'ORADB' SCOPE = BOTH;

# no need to set DB_FILE_NAME_CONVERT, as the standby system has the same directory structure
SHOW PARAMETER DB_FILE_NAME_CONVERT;

# Get list of directory-dependent parameters and create the directories in the standby server:
COL NAME FORMAT A40
COL VALUE FORMAT A100
SELECT NAME, VALUE FROM V$PARAMETER WHERE UPPER(VALUE) LIKE UPPER('%/oradb/%');


--Set CONTROL_FILE_RECORD_KEEP_TIME parameter 
SHOW PARAMETER CONTROL_FILE_RECORD_KEEP_TIME;
ALTER SYSTEM SET CONTROL_FILE_RECORD_KEEP_TIME = 30 SCOPE = BOTH;

--Create a password file, if there is not one
ls -l /u01/app/oracle/product/19.0.0/db_1/dbs/orapworadb

ALTER USER SYS IDENTIFIED BY manager cotainer=all;
orapwd file=$ORACLE_HOME/dbs/orapw<SID> password=<sys_password> format=12
orapwd file=$ORACLE_HOME/dbs/orapworadb password=manager format=12


check and update local_listener parameter value with new hostname or ip address
ALTER SYSTEM SET local_listener='(ADDRESS = (PROTOCOL=TCP)(HOST=primary.localdomain)(PORT=1521))' scope=both;


Configure Listener 

[oracle@primary admin]$ cat listener.ora
# listener.ora Network Configuration File: /u01/app/oracle/product/19.0.0/db_1/network/admin/listener.ora
# Generated by Oracle configuration tools.
LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.21)(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = oradb)
      (ORACLE_HOME = /u01/app/oracle/product/19.0.0/db_1)
      (SID_NAME = oradb)
    )
    (SID_DESC =
      (GLOBAL_DBNAME = oradb_DGMGRL)
      (ORACLE_HOME = /u01/app/oracle/product/19.0.0/db_1)
      (SID_NAME = oradb)
    )
  )

ADR_BASE_LISTENER = /u01/app/oracle




Configure the tnsnames.ora file:

[oracle@primary admin]$ cat tnsnames.ora
# tnsnames.ora Network Configuration File: /u01/app/oracle/product/19.0.0/db_1/network/admin/tnsnames.ora
# Generated by Oracle configuration tools.

ORADB =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.21)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = oradb)
    )
  )


ORADB_S2 =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.22)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = oradb)
    )
  )




Configure sqlnet.ora file

[oracle@primary admin]$ cat sqlnet.ora
NAMES.DIRECTORY_PATH=(TNSNAMES, EZCONNECT, LDAP)




test configuration:
tnsping oradb 
tnsping oradb_s2


# See which Oracle home is active
echo $ORACLE_HOME

# Check TNS_ADMIN override
echo $TNS_ADMIN


--Update bash_profile 

[oracle@primary ~]$ cat .bash_profile
# .bash_profile
if [ -f ~/.bashrc ]; then
. ~/.bashrc
fi
ORACLE_BASE=/u01/app/oracle; export ORACLE_BASE
ORACLE_SID=oradb; export ORACLE_SID
ORACLE_HOME=$ORACLE_BASE/product/19.0.0/db_1; export ORACLE_HOME
NLS_DATE_FORMAT="DD-MON-YYYY HH24:MI:SS"; export NLS_DATE_FORMAT
TNS_ADMIN=$ORACLE_HOME/network/admin; export TNS_ADMIN
PATH=$PATH:$HOME/.local/bin:$HOME/bin
PATH=${PATH}:/usr/bin:/bin:/usr/local/bin
PATH=.:${PATH}:$ORACLE_HOME/bin
export PATH
LD_LIBRARY_PATH=$ORACLE_HOME/lib
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$ORACLE_HOME/oracm/lib
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/lib:/usr/lib:/usr/local/lib
export LD_LIBRARY_PATH
CLASSPATH=$ORACLE_HOME/JRE
CLASSPATH=${CLASSPATH}:$ORACLE_HOME/jlib
CLASSPATH=${CLASSPATH}:$ORACLE_HOME/rdbms/jlib
CLASSPATH=${CLASSPATH}:$ORACLE_HOME/network/jlib
export CLASSPATH
export TEMP=/tmp
export TMPDIR=/tmp
umask 022
alias dba='sqlplus / as sysdba'
alias sql='sqlplus / as sysdba'
alias dbs='cd $ORACLE_HOME/dbs'
alias net='cd $ORACLE_HOME/network/admin'
alias trace='cd $ORACLE_BASE/diag/rdbms/oradb/oradb/trace'
alias cls='clear'
alias dir='ls -lart'
alias h='cd ~oracle'





STANDBY 
=======
su - oracle 

mkdir -p /u01/app/oracle/admin/oradb
mkdir -p /u01/app/oracle/admin/adump
mkdir -p /u01/app/oracle/admin/oradb/cdump 
(This is optional as we are using same path both sides)



LISTENER 
========
[oracle@standby admin]$ cat listener.ora
LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.22)(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = oradb)
      (ORACLE_HOME = /u01/app/oracle/product/19.0.0/db_1)
      (SID_NAME = oradb)
    )
         (SID_DESC =
      (GLOBAL_DBNAME = oradb_DGMGRL)
      (ORACLE_HOME = /u01/app/oracle/product/19.0.0/db_1)
      (SID_NAME = oradb)
    )
  )

ADR_BASE_LISTENER = /u01/app/oracle





tnsnames.ora
============
[oracle@standby admin]$ cat tnsnames.ora
ORADB =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.21)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = oradb)
    )
  )

ORADB_S2 =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.22)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = oradb)
    )
  )


sqlnet.ora  
==========
[oracle@standby admin]$ cat sqlnet.ora
NAMES.DIRECTORY_PATH=(TNSNAMES, EZCONNECT, LDAP)



on primary create pfile:
CREATE PFILE FROM SPFILE;

--copy the password file from primary to standby 
scp orapworadb oracle@192.168.1.22:/u01/app/oracle/product/19.0.0/db_1/dbs/orapworadb_s2

--copy pfile to the standby 
scp initoradb.ora oracle@192.168.1.22:/u01/app/oracle/product/19.0.0/db_1/dbs/initoradb_s2.ora

--edit pfile on standby
*.db_name='oradb'
*.DB_UNIQUE_NAME='PUNE'
*.FAL_SERVER='oradb'
*.FAL_CLIENT='oradb_s2'
*.local_listener='(ADDRESS = (PROTOCOL=TCP)(HOST=standby.localdomain)(PORT=1521))'
*.log_archive_dest_2='SERVICE=ORADB ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=HYD'


--keep the standby server on nomount mode  
--keep the primary database on mount mode  

On Primary Server 
=================
rman target sys/manager@oradb auxiliary sys/manager@oradb_s2

DUPLICATE TARGET DATABASE FOR STANDBY FROM ACTIVE DATABASE NOFILENAMECHECK;


Login to standby server: after rman DUPLICATE this must be in mount mode:

To start and stop MRP:
For Active Data Guard, OPEN_MODE should show READ ONLY WITH APPLY, meaning the standby is open for reads while MRP is applying redo simultaneously.

ALTER DATABASE RECOVER MANAGED STANDBY DATABASE USING CURRENT LOGFILE DISCONNECT FROM SESSION;
ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION;
ALTER DATABASE RECOVER MANAGED STANDBY DATABASE CANCEL;

SELECT PROCESS,THREAD#,SEQUENCE#,STATUS,BLOCK# FROM V$MANAGED_STANDBY;

SELECT PROCESS, STATUS, THREAD#, SEQUENCE#, BLOCK#
FROM V$MANAGED_STANDBY
WHERE PROCESS = 'MRP0';


-- Check apply lag
SELECT NAME, VALUE, DATUM_TIME
FROM V$DATAGUARD_STATS
WHERE NAME IN ('apply lag','transport lag');

-- Check database role and protection mode
SELECT DB_UNIQUE_NAME, DATABASE_ROLE, OPEN_MODE, PROTECTION_MODE
FROM V$DATABASE;








DGMGRL SETUP:

make sure this entry was there in listener.ora file on both sides:
(SID_DESC=
     (GLOBAL_DBNAME=proddb_DGMGRL)
     (SID_NAME=proddb)
     (ORACLE_HOME=/u01/app/oracle/product/11.2.0/dbhome_1)
   )

Stop MRP on standby:
alter database recover managed standby database cancel;

clear Log_Archive_dest_2 parameter on both sides:
alter system set LOG_ARCHIVE_DEST_2 = '' SCOPE = BOTH sid = '*';

Enable broker on both sides:
On primary:
===========
SQL> alter system set dg_broker_start = true;
SQL> show parameter dg_broker_start;

On standby:
===========
SQL> alter system set dg_broker_start = true;
SQL> show parameter dg_broker_start;


Register primary with broker:

On primary, connect to DGMGRL utility and register the primary database with broker

On primary:
===========
dgmgrl sys/manager@oradb
DGMGRL> create configuration 'my_dg' as primary database is HYD connect identifier is oradb;
DGMGRL> show configuration;


Register standby with broker:

In the same DGMGRL utility, register standby from primary server itself

DGMGRL> add database PUNE as connect identifier is oradb_s2;
DGMGRL> show configuration;


Enable Data Guard broker:

Once primary and standby are registered, we must enable broker.

DGMGRL> ENABLE CONFIGURATION;
DGMGRL> SHOW CONFIGURATION;
DGMGRL> SHOW DATABASE oradb;
DGMGRL> SHOW DATABASE VERBOSE oradb;
DGMGRL> SHOW DATABASE oradb_s2;
DGMGRL> SHOW DATABASE VERBOSE oradb_s2;


Manage Redo Apply via Broker:

Like how we start/stop MRP manually, we can start/stop redo apply on standby using broker

Stop log apply:
===============
dgmgrl sys/manager@oradb
DGMGRL> show configuration;
DGMGRL> show database oradb_s2;
DGMGRL> edit database oradb_s2 set state=APPLY-OFF;
DGMGRL> show database oradb_s2;

Start log apply:
================
dgmgrl sys/manager@oradb
DGMGRL> show configuration;
DGMGRL> show database oradb_s2;
DGMGRL> edit database oradb_s2 set state=APPLY-ON;
DGMGRL> show database oradb_s2;


Start/stop log shipping via Broker:

How we can manually enable log shipping from primary to standby, the same way we 
can use broker to enable log shipping.

Disable log shipping/transport:
===============================
dgmgrl sys/@oradb
DGMGRL> show configuration;
DGMGRL> show database oradb;
DGMGRL> edit database oradb set state=TRANSPORT-OFF;
DGMGRL> show database oradb;

Enable log shipping/transport:
==============================
dgmgrl sys/@oradb
DGMGRL> show configuration;
DGMGRL> show database oradb;
DGMGRL> edit database oradb set state=TRANSPORT-ON;
DGMGRL> show database oradb;




dgmgrl issues:

ALTER SYSTEM SET local_listener='(ADDRESS = (PROTOCOL=TCP)(HOST=192.168.1.21)(PORT=1521))' SCOPE=BOTH;


DGMGRL> EDIT DATABASE 'HYD' SET PROPERTY StaticConnectIdentifier='(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.1.21)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=oradb_DGMGRL)(INSTANCE_NAME=oradb)(SERVER=DEDICATED)))';

EDIT DATABASE 'PUNE' SET PROPERTY StaticConnectIdentifier='(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.1.22)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=oradb_DGMGRL)(INSTANCE_NAME=oradb)(SERVER=DEDICATED)))';
