Physical Standby

Step 1. Enable archivelog mode and Force logging

select log_mode from v$database;
shut immediate;
startup mount
alter database archivelog;
alter database force logging;
select name,force_logging,log_mode from v$database;

Step 2. Create standby redologfiles

select group#,member,type,status from v$logfile;

alter database add standby logfile group 11 '/u02/app/oracle/oradata/DIGITAL/redo04.log'  size 50m;
alter database add standby logfile group 12 '/u02/app/oracle/oradata/DIGITAL/redo05.log' size 50m;
alter database add standby logfile group 13 '/u02/app/oracle/oradata/DIGITAL/redo06.log' size 50m;
alter database add standby logfile group 14 '/u02/app/oracle/oradata/DIGITAL/redo07.log' size 50m;

Step 3. Create TNS entry for both (Primary & Standby)

Primary Side

DIGITAL =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = ocptechnology.localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = digital)
    )
  )


DIGITALDR =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = ocpstandby.localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = digitaldr)
    )
  )



Primary Side Listener Entry:

cat listener.ora
# listener.ora Network Configuration File: /u02/app/oracle/product/19.3.0/db_home/network/admin/listener.ora
# Generated by Oracle configuration tools.

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = digital)
      (ORACLE_HOME = /u02/app/oracle/product/19.3.0/db_home)
      (SID_NAME = digital)
    )
  )

LISTENER =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = ocptechnology.localhost)(PORT = 1521))
  )

ADR_BASE_LISTENER = /u02/app/oracle


Standby side listener entry:

[oracle@ocpstandby admin]$ cat listener.ora
# listener.ora Network Configuration File: /u02/app/oracle/product/19.3.0/db_home/network/admin/listener.ora
# Generated by Oracle configuration tools.

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = digitaldr)
      (ORACLE_HOME = /u02/app/oracle/product/19.3.0/db_home)
      (SID_NAME = digitaldr)
    )
  )

LISTENER =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = ocpstandby.localhost)(PORT = 1521))
  )

ADR_BASE_LISTENER = /u02/app/oracle



Check TNS ping

$tnsping digital
$tnsping digitaldr


How to disable Firewall

# sudo firewall-cmd --state
running

# sudo systemctl stop firewalld
# sudo systemctl disable firewalld
Removed symlink /etc/systemd/system/multi-user.target.wants/firewalld.service.
Removed symlink /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service.


# sudo firewall-cmd --state
not running


https://ocptechnology.com/oracle-19c-dataguard-setup-with-pdb/